# These are supported funding model platforms

github: DevNullInc
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: stygianrenegade
custom: https://cash.app/$StygianRenegade/1.00,https://cash.app/$StygianRenegade/5.00,https://cash.app/$StygianRenegade/10.00
