# These are supported funding model platforms

github: DevNullInc
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: stygianrenegade
custom: https://www.paypal.com/ncp/payment/ME25M8VZRNSEN
